### ISSUE TITLE
It loads the Spotify page, I request OAuth, then it loads that 404, then it loads a blank play.google.com/music page

### ISSUE THREAD

**Issue by 19007361** [jordam/Portify.JS#11]

**Comment by exadeci** [comment]
It seems that listen.js has been removed to be replaced by listen_extended_[hash].js

**Comment by dantebertana** [comment]
Is there a fix in the works?

**Comment by ChrisTrivedi** [comment]
I'm seeing the same thing. Any help is greatly appreciated!

**Comment by exadeci** [comment]
I used his Python version https://github.com/jordam/ezportify your google password is required but it's a good occasion to change it after.

**Comment by Drakot** [comment]
It shows this error when trying to execute the python file.

`File "ezportify.py", line 3, in <module>
    from google import Mobileclient
  File "/Users/Me/Downloads/ezportify-master/google.py", line 1, in <module>
    import certifi
ImportError: No module named certifi`

**Comment by exadeci** [comment]
@Drakot That should have been on the other project issues but anyway, it's telling you that it can't find a module named `certifi` so you have to install it with either `pip install certifi` **or** `easy_install certifi` same for the other module that will be missing..

**Comment by Drakot** [comment]
Sorry, I posted this message in the wrong repository.

**Comment by jordam** [comment]
Ok ok, I got around to taking a crack at this again. It looks like the new listen_extended is letting me ajax it in so it's an easy fix now :)

Should be working, as long as the listen_extended url length is the same for all of us. Its a hacky patch but hopefully it gets the ball rolling again.

**Comment by 19007361** [comment]
Thank you so much dev! Unfortunately, while it reaches Play Music and opens the Portify prompt, it doesn't seem to do anything after I select "import" and leave the naming for the playlists blank.

**Comment by kyds3k** [comment]
I'm getting the same result as the previous poster. Any updates?
