### ISSUE TITLE
Google Music > Spotify doesn't work

### ISSUE THREAD

**Issue by davisstu** [jordam/Portify.JS#13]
The process gets as far as loading Google Music, allows you to select your playlist(s), then offers you the chance to Push to Spotify, I give it a prefix and get the following error you see on the screenshot.

Can replicate the issue over a number of browsers and platforms.

Browser is Chrome Beta, using the (new) Chrome Portify.js bookmarklet.

![screenshot-play google com 2016-05-29 07-32-01](https://cloud.githubusercontent.com/assets/8912521/15631724/946e7394-256f-11e6-8cdb-d4d5b5f2bd42.jpeg)

**Comment by JoelJ** [comment]
It didn't work for me either (Chrome  50.0.2661.102 (64-bit) on OS X). But I did get it to work when I chose specific playlists rather than selecting "Import them All".
