### ISSUE TITLE
When requesting OAuth from, nothing happens after I get the key

### ISSUE THREAD

**Issue by Frostcrest** [jordam/Portify.JS#14]
I load up music.google and click the Portify.JS bookmark. It redirects to the OAuth, I get the playlist-read-private key, but then nothing happens. There is no popup or prompt on music.google.

**Comment by merlinschumacher** [comment]
I have the same issue in Chrome. Also the transfer doesn't seem to work in Firefox. It seems that the css breaks a bit (white text everywhere) but there is not feedback on import

**Comment by jacko301** [comment]
I have the exact same issue in chrome. Please fix soon as I want to stop using Spotify before more terrible changes happen.

**Comment by davisstu** [comment]
Yes this has been mentioned a few times, including in my previous Issue - hopefully, the owner will fix it soon - he looked like he's abandoned it previously but then did a lot of work to get it updated.

**Comment by koenhendriks** [comment]
Same here

**Comment by JoeyWoah** [comment]
Same here. Both browser versions are bugged.

**Comment by CosmicShiv** [comment]
Is there any fix yet?

**Comment by mlys9138** [comment]
Same issue
