### ISSUE TITLE
Stuck on creating google playlists

### ISSUE THREAD

**Issue by klapperkopp** [jordam/Portify.JS#16]
When trying to copy from Spotify to Google Music it gets stuck on creating the last selected playlist. It opens up the window for creating it and selects the text for the name, but that's it.

**Comment by JoeyWoah** [comment]
Having the same issue on Safari. Just gets hung up on the last Create Playlist. I couldn't get the Chrome version to work.

**Comment by ghost** [comment]
Same here - Playlists get created but they are all empty.

**Comment by zackwithak13** [comment]
Same problem for me using Chrome or Firefox

**Comment by matthewkirk203** [comment]
Same for me. It will create empty playlists if I try and import several Spotify playlists.

**Comment by Fackelmann** [comment]
I have the same issue on Firefox 50.1.0
