### ISSUE TITLE
Google Updated it playlist display

### ISSUE THREAD

**Issue by gouveia00** [jordam/Portify.JS#17]
Google has updated (afaik just yesterday) the way playlists are displayed, so we get a total of 0 playlists found. I'm trying to tinker around the code, but from what I've could find, the new element that should be searched for (so we can know which playlists are there) is $("#playlists-container div[data-type='pl']"), but I'm having trouble with getting all of the elements that fall under that category (I'm just tinkering with Chrome's own console).

**Comment by fishouttah20** [comment]
Brilliant timing, just found this and thought it had solved all my problems :( Lots of moral support and good vibes to any maintainers.

**Comment by gouveia00** [comment]
I know, I was just going to fully switch from GMusic to Spotify, since I'm using more of the social capabilities than the "your own MP3 in the cloud" feature. This tool works perfectly, from what I've already used. I'm trying to get it to work on my end, hopefully I'll be able to least help the devs.

**Comment by fishouttah20** [comment]
If you just have a few playlists you can use unportify JavaScript (injected into Google play with an extension) to get a json text file, convert the json to a CSV (konklone.io/json) and then paste it into www.playlist-converter.net which can convert and add to your Spotify account. 

Would much prefer to see this fixed though!
