### ISSUE TITLE
Google play issue

### ISSUE THREAD

**Issue by projectglue** [jordam/Portify.JS#19]
Hi there,

After getting the token, i click on the bookmark 1 more time to load google music, but google music wont load.
It gets stuck trying to load the page and the page just comes up blank.
I tried this in google chrome and firefox.

**Comment by Edinburgher** [comment]
Same issue, also Chrome

**Comment by projectglue** [comment]
Does anyone know if there is a work around this, or another app we can use?

**Comment by prediscover** [comment]
same issue

**Comment by monicoomar** [comment]
That happens to me when running it on chrome, now when using firefox it seems that starts to add all the songs from the playlist but when is done, there is no playlist nor nothing on Google Play can you check on that please

**Comment by lusky3** [comment]
Confirmed I am also getting a blank page on Chrome after the 404. Chrome 54.0.2840.27

**Comment by jean-bon** [comment]
hello, i am also getting the blank page on url https://play.google.com/music/portifyjs?spotifyoauth=blablabla ...

**Comment by JoshStegmeier** [comment]
I'm also getting the blank page on Google Music after the 404 on Chrome.

**Comment by jordam** [comment]
I've pulled the fix posed by Maarcosd. Let me know how it goes guys!

**Comment by SpacebarStar** [comment]
Well, Google Play Music does open up now on Chrome, but it only creates the playlists and when the searching for the songs is done, all I end up with are empty playlists.
