### ISSUE TITLE
Google Play playlist is empty

### ISSUE THREAD

**Issue by UnaiYecora** [jordam/Portify.JS#21]
It doesn't seem to be loading the songs into the playlist. It runs normally, and finishes like always, but when I go to the new playlist, it's empty.

**Comment by SpacebarStar** [comment]
Yup, same problem here

**Comment by CaptainClueless** [comment]
Same here. My console says:
`listen__en_gb.js:900 Uncaught CustomError: Error in protected function: Cannot read property 'fire' of undefined`

**Comment by Qix-** [comment]
Getting:

```
Uncaught CustomError: Error in protected function: x is not a function
    c @ listen.js:620
    (anonymous function) @ listen.js:54
    fire @ sj_srcs.js:4152
    addSongToPlaylist @ portify.js?_=1477215376202:139
    tickLauncher @ portify.js?_=1477215376202:323
    c @ listen.js:620
```

**Comment by gysi** [comment]
Same here
![screen shot 2016-10-26 at 11 19 41](https://cloud.githubusercontent.com/assets/1576445/19720379/2d2e8ce4-9b6e-11e6-9ff7-48004829f3eb.png)

**Comment by archer007** [comment]
Same here as well.

![image](https://cloud.githubusercontent.com/assets/86111/19916675/a1dc9a4e-a079-11e6-8fc9-53d09b63fe0f.png)

**Comment by GoWithitRoger** [comment]
Same with me.

**Comment by drrobotnic** [comment]
Same

**Comment by cordell** [comment]
came to report, but looks like its known issue. the playlist titles are made going from spotify to google, but the playlists are empty.

**Comment by ebcarty** [comment]
Came to report the same - Playlists are created automatically (except for the last one, had to click "Create"), but then there are no songs being loaded into the playlists.
![2017-01-08_17-25-41](https://cloud.githubusercontent.com/assets/13952816/21755360/8639bfaa-d5c7-11e6-91f8-03780936adaa.png)

**Comment by Plockets** [comment]
Just adding my voice to the masses with this problem, although I would guess it won't get fixed unless someone else picks up the project at this point. I am curious if it works for anyone anymore? Seems like some change in a Chrome update or the way Play/Spotify songs are referenced may have broken the script.

**Comment by trogdoor17** [comment]
Same issue as Plockets, I hope that this project is still being developed. It seems that GPM has had an update that breaks this script. I'm getting a "I see 0 playlists" prompt.

**Comment by disambiguator** [comment]
Yeah, I figure this is not being developed any more. I switched over to using [pyportify](https://github.com/rckclmbr/pyportify) which seems to work well.

**Comment by cubiczx** [comment]
The same problem Playlist created with 0 songs

**Comment by Zerqz** [comment]
Same problem here.
