### ISSUE TITLE
Portify creates multiple copies of the same playlists

### ISSUE THREAD

**Issue by coagmano** [jordam/Portify.JS#22]
After running portify, I have multiple copies of every playlist being transferred. Most of them are completely empty, but in some cases the songs from a spotify playlist are split between the copies of the playlist in GPM

**Comment by theDevelopper** [comment]
Having the same issue. Multiple playlists with same name and all of mine are empty

**Comment by coagmano** [comment]
Tried it again with less playlists (first 1, then 2, then 3) and it worked perfectly. Probably just struggling to handle so many playlists and tracks rather than a genuine bug

**Comment by dam13n** [comment]
Instead of around 20 Playlists, I have 172 EMPTY playlists. Is there a way to delete them without doing it 1 at a time? : (

**Comment by dam13n** [comment]
In case anyone has this issue and doesn't want to manually delete all the empty playlists, here's a short Python script that deletes all your playlists (need to modify it a bit if you just want to delete empty ones):
`$ pip install gmusicapi`

```
from gmusicapi import Mobileclient
api = Mobileclient()
api.login(email, password, '1234567890abcdef' , Mobileclient.FROM_MAC_ADDRESS)
pl = api.get_all_playlists(False, False)

for p in pl:
    api.delete_playlist(p['id'])
```

**Comment by theDevelopper** [comment]
Tested with single playlist: not working. It is simply not adding the song, but the songs are clearly found.

Please can someone fix this

**Comment by betterbydesign** [comment]
Same here, but I did with multiple playlists. Tried the delete feature too and it did nothing

**Comment by julianwue** [comment]
with playlists same problem & no import possible at all

**Comment by jean-bon** [comment]
Hello
I have the same problem as everyone here : import from spotify to Google seems OK, but in the end, playlists are empty.
As soon as it's fixed i will cease my Spotify subscribtion ..!
Please, fix it :)
Thanks for your work
Anthony

**Comment by brando-online** [comment]
Glad I'm not the only one having this issue :)

**Comment by davidlavy88** [comment]
Same issue here. Now I have a bunch of empty playlists

**Comment by betterbydesign** [comment]
Honestly I just used Stamps, I wasn't taking the chance again.

-------


Thanks,Scott Foster








Scott Foster/Owner / Developer


Satori Design LLCOffice: 215-478-8171 ext.1
http://www.satori-design.com



This e-mail message may contain confidential or legally privileged information
and is intended only for the use of the intended recipient(s). Any unauthorized
disclosure, dissemination, distribution, copying or the taking of any action in
reliance on the information herein is prohibited. E-mails are not secure and
cannot be guaranteed to be error free as they can be intercepted, amended, or
contain viruses. Anyone who communicates with us by e-mail is deemed to have
accepted these risks. Satori Design is not responsible for errors or omissions
in this message and denies any responsibility for any damage arising from the
use of e-mail. Any opinion and other statement contained in this message and any
attachment are solely those of the author and do not necessarily represent those
of the company.







On Fri, Dec 9, 2016 8:41 PM, David Lavy notifications@github.com
wrote:
Same issue here. Now I have a bunch of empty playlists

**Comment by brando-online** [comment]
Me too. Bought stamps and it worked perfectly.

**Comment by coagmano** [comment]
This stopped working for me as well
I ended up using [PyPortify](https://github.com/rckclmbr/pyportify) the second time around and it worked perfectly

**Comment by Ronnny24** [comment]
You can add music playlist using from MusConv.com

**Comment by Ronnny24** [comment]
You can add music playlist by using musConv.com

**Comment by fredbrwn** [comment]
you can use MusConv.com tool to resolve the problem related to portify.
