### ISSUE TITLE
Error adding Songs

### ISSUE THREAD

**Issue by JayAhrDe** [jordam/Portify.JS#23]
Import stops after creating Playlists, twice or even three times each, leaving them empty.

This is what Console reports:
![image](https://cloud.githubusercontent.com/assets/930553/23172300/9eaa2952-f855-11e6-9947-c7baa52cda00.png)

**Comment by biiome** [comment]
Yeah I have the same problem. I just get an empty playlist... nothing more :(

**Comment by stagrim** [comment]
Same here, it just gets stuck with the only result being an empty playlist.

**Comment by drpfenderson** [comment]
Same issue here, with a couple more errors.

![image](https://cloud.githubusercontent.com/assets/7515881/23571118/511ea716-001c-11e7-932b-ea62b8204385.png)

A similar error scrolls a few times, but returns empty playlist.

**Comment by fohtoh** [comment]
I am also getting this.  I have tried in chrome and firefox.  Both get to the point of creating the playlist, but no songs get added to the playlist.
Glad this is already logged, hope we can get this resolved :)

**Comment by ImOnMars** [comment]
This issue is still happening. I just get either an empty playlist or only the very first song being added.

**Comment by integraldesign** [comment]
The same problems playlist created with 0 songs

**Comment by cubiczx** [comment]
The same problem Playlist created with 0 songs

**Comment by cubiczx** [comment]
The same problem Playlist created with 0 songs

**Comment by iainrosen** [comment]
Same here.

**Comment by cubiczx** [comment]
I solve this problem removing not available songs of my lists
