### ISSUE TITLE
Does not work?

### ISSUE THREAD

**Issue by No0Vad** [jordam/Portify.JS#3]
Hi,

I recommend changing https://github.com/jordam/Portify.JS/blob/master/express.js#L76 to
https://play.google.com/music/listen?u=0&hl=en-US
`'https:\/\/play.google.com\/music\/listen?u\x3d0\x26hl\x3den-US'`

To force english, otherwise the listen.js file is named different. Danish its listen_da.js instead.

Also, something looks broken.
The script tries to load
`https://play-music.gstatic.com/fe/4f7438cf040a6cef28d32b902344dfee/listen.js%22%3E%3C/script%3E%3Cdiv%20class=%22gb_Xa%22%3E%3C/div%3E%3Cscript%20type=%22text/javascript%22%3E%3C/script%3E%3C/body%3E%3C/html%3E/sj_srcs.js`

Then nothing happens when I return.

**Comment by jordam** [comment]
Good point, I think other parts of the script might get buggy if the language is different anyways.

I've updated it to force english and I've rewrote part of the script that I think was throwing that error.

Thanks for the pointers and let me know how it goes!

**Comment by No0Vad** [comment]
I get the modal dialog now :+1: When I choose to import all playlists, I get this Error
`Uncaught TypeError: Cannot read property 'length' of undefined`

Pointing to this line:
https://github.com/jordam/Portify.JS/blob/master/portify.js#L745

Almost like Case 1 never gets executed?

If I paste row 731 into the console `getItems('https://api.spotify.com/v1/me/playlists', 'gotpl', gotPlaylists, []);`
I get a list, but double modalboxes.

**Comment by jordam** [comment]
Yeah, that was a bit tricky, looks like my oauth modal called back to my reprompt function synchronously causing it to run the oauth stub, then the prefix modal, then add 1 to the stage for oauth, then add 1 to stage for prefixmodal.

Should be patched up, let me know if the system as a whole is working for you now.

**Comment by No0Vad** [comment]
The whole system works now! :smiley: 
My Spotify playlists has successfully been imported.

Thank you for this awesome utility, that does not rely on Ruby and/or Python.

**Comment by jordam** [comment]
Glad to hear! Thanks for helping debug!
