### ISSUE TITLE
Not working with latest Chrome or Firefox?

### ISSUE THREAD

**Issue by Stampede10343** [jordam/Portify.JS#9]
I've been trying to import from Spotify to Play music and I tried both Chrome and Firefox with no luck. It still gets the oath token but it just sits at the play music home page

**Comment by Stampede10343** [comment]
![image](https://cloud.githubusercontent.com/assets/5996253/14034942/c6766b8e-f1fe-11e5-9eb2-397bbe75a972.png)

**Comment by brunofin** [comment]
I'm getting the same error. Sad thing is that one week ago I imported to another Google account and it worked :(

I can't understand why Google won't make an API to Google Play Music, it would make this whole thing much simpler.

**Comment by jordam** [comment]
Yeah, the other issue is actually refering the the glitch. Google patched up their security within a few weeks of me making this. I need to recode it to bypass their patch. I've been way busy though unfortunately.

The core issue is that google no longer allows me to ajax load the listen.js and sj_srcs javascript. I have a fix for this, but I need to code it out sometime.

 What needs to happen is the script needs to go from spotify to google play. It needs to pick up that script hash (the /HASH/listen.js one). Then it needs to move to the listen.js page itself. It copies the contents, b64's them, then moves to sj_srcs.js while appending the b64'd js as a url parameter. Then it does the same routine with sj_srcs.js, pushes back to the /portifyjs endpoint, and continues with the process while injecting the scripts from the b64 url parameters rather then trying to ajax load it.

Unfortunately, this will add at least three extra clicks of the bookmark, and a bit of user confusion as we take them through two pages of raw javascript in the process.

When I get a chance I want to implement it, but I'm also open to pull requests _hint hint_

**Comment by Stampede10343** [comment]
I'm not opposed to looking into it. I quite dislike javascript, but It's probably quicker to fix this than manually import my playlists.. haha. I'll have to look into this some more, but I'll try. Any tips for JavaScript development and testing this?

**Comment by jordam** [comment]
Patched 5/23/15. Please test. Google is letting me ajax their new listen_extended.js so I'm just not gonna question it.

**Comment by ionred** [comment]
looks good. thanks @jordam

**Comment by Stampede10343** [comment]
Works Chrome! Thanks. Sorry I wasn't much help. JS isn't my strong point
